# Generated by Django 3.2.4 on 2021-11-10 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountRecords',
            fields=[
                ('txn_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('account_serial', models.TextField()),
                ('financial_year', models.TextField()),
                ('type', models.TextField()),
                ('add_to_cash_in_hand', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('add_to_cash_in_bank', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('add_to_current_balance', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('txn_time', models.DateTimeField()),
                ('txn_ref_id', models.TextField()),
                ('login_user', models.TextField()),
            ],
            options={
                'db_table': 'accountsrecords',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('account_serial', models.TextField(primary_key=True, serialize=False)),
                ('financial_year', models.TextField()),
                ('account_name', models.TextField()),
                ('account_number', models.TextField()),
                ('bank_name', models.TextField()),
                ('is_active', models.BooleanField()),
                ('opening_balance', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('closing_balance', models.DecimalField(decimal_places=2, max_digits=1000, null=True)),
                ('current_balance', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('cash_in_hand', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('cash_in_bank', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('description', models.TextField(null=True)),
            ],
            options={
                'db_table': 'accountsfinance',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AccountTransactionRecords',
            fields=[
                ('txn_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('account_serial', models.TextField()),
                ('financial_year', models.TextField()),
                ('account_name', models.TextField()),
                ('account_number', models.TextField()),
                ('bank_name', models.TextField()),
                ('type', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('description', models.TextField(null=True)),
                ('txn_time', models.DateTimeField()),
                ('login_user', models.TextField()),
            ],
            options={
                'db_table': 'accountstransactionrecords',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Dues',
            fields=[
                ('due_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('due_display_id', models.TextField()),
                ('due_financial_year', models.TextField()),
                ('due_type', models.TextField()),
                ('due_amount', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('due_fineamt', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('is_head', models.IntegerField()),
                ('is_retired', models.IntegerField()),
                ('is_nonresident', models.IntegerField()),
                ('is_govt', models.IntegerField()),
                ('is_male', models.IntegerField()),
                ('due_active', models.IntegerField()),
                ('account_serial', models.TextField()),
                ('applied', models.BooleanField()),
                ('paid_together', models.BooleanField()),
            ],
            options={
                'db_table': 'dues',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('txn_id', models.TextField(primary_key=True, serialize=False)),
                ('txn_auto_id', models.IntegerField()),
                ('txn_financial_year', models.TextField()),
                ('txn_type', models.TextField()),
                ('txn_due_id', models.TextField()),
                ('txn_amount', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('txn_member', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('txn_family', models.IntegerField()),
                ('txn_date', models.DateTimeField()),
                ('txn_remarks', models.TextField()),
                ('account_serial', models.TextField()),
                ('login_user', models.TextField()),
            ],
            options={
                'db_table': 'ledger',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MemberFamilyChanges',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('serial', models.TextField()),
                ('old_family', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('new_family', models.DecimalField(decimal_places=2, max_digits=1000)),
            ],
            options={
                'db_table': 'memberfamilychanges',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('serial', models.BigAutoField(primary_key=True, serialize=False)),
                ('financial_year_serial', models.TextField()),
                ('family_number', models.IntegerField()),
                ('family_name', models.TextField()),
                ('member_number', models.DecimalField(decimal_places=3, max_digits=1000)),
                ('name_eng', models.TextField()),
                ('is_active', models.BooleanField()),
                ('is_head', models.BooleanField()),
                ('is_due_apply', models.BooleanField()),
                ('is_retired', models.BooleanField()),
                ('is_nonresident', models.BooleanField()),
                ('is_govt', models.BooleanField()),
                ('is_male', models.BooleanField()),
                ('is_alive', models.BooleanField()),
                ('age', models.IntegerField()),
                ('area', models.TextField()),
                ('address', models.TextField(null=True)),
                ('postbox', models.TextField(null=True)),
                ('mobile', models.BigIntegerField(null=True)),
                ('email', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('remarks', models.TextField(null=True)),
            ],
            options={
                'db_table': 'members',
                'ordering': ['serial'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Receipts',
            fields=[
                ('receipt_id', models.TextField(primary_key=True, serialize=False)),
                ('receipt_auto_id', models.IntegerField()),
                ('receipt_financial_year', models.TextField()),
                ('receipt_due_id', models.TextField()),
                ('receipt_member', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('receipt_family', models.IntegerField()),
                ('receipt_date', models.DateTimeField()),
                ('receipt_amount', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('account_serial', models.TextField()),
                ('login_user', models.TextField()),
                ('txn_id', models.TextField()),
                ('is_active', models.BooleanField()),
            ],
            options={
                'db_table': 'receipts',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ReceiptsInvoice',
            fields=[
                ('receipt_invoice_id', models.TextField(primary_key=True, serialize=False)),
                ('receipt_invoice_auto_id', models.IntegerField()),
                ('receipt_financial_year', models.TextField()),
                ('family_no', models.IntegerField()),
                ('receipt_ids', models.TextField()),
                ('receipt_date', models.DateTimeField()),
                ('login_user', models.TextField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('is_active', models.BooleanField()),
                ('remarks', models.TextField()),
            ],
            options={
                'db_table': 'receiptsinvoice',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sitewide',
            fields=[
                ('financial_id', models.IntegerField(primary_key=True, serialize=False)),
                ('financial_term_code', models.TextField()),
                ('financial_year', models.TextField()),
                ('year_start_date', models.DateField()),
                ('year_end_date', models.DateField()),
                ('description', models.TextField(default='2019-07-23')),
            ],
            options={
                'db_table': 'sitewide',
                'managed': True,
            },
        ),
    ]
