# Generated by Django 3.2.4 on 2021-07-13 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vouchers',
            fields=[
                ('voucher_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('voucher_financial_year', models.TextField()),
                ('voucher_reference_id', models.TextField()),
                ('voucher_type', models.TextField()),
                ('voucher_amount', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('remarks', models.TextField()),
                ('voucher_head', models.TextField()),
                ('voucher_subhead', models.TextField()),
                ('voucher_date', models.DateField()),
            ],
            options={
                'db_table': 'vouchers',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VoucherTypes',
            fields=[
                ('serial', models.TextField(primary_key=True, serialize=False)),
                ('financial_year_serial', models.TextField()),
                ('account_serial', models.TextField()),
                ('voucher_head', models.TextField()),
                ('voucher_subhead', models.TextField()),
                ('type', models.TextField()),
                ('is_active', models.BooleanField()),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'voucher_types',
                'managed': True,
            },
        ),
    ]
