# Generated by Django 3.2.4 on 2021-07-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0002_vouchers_account_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vouchers',
            name='voucher_member_address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vouchers',
            name='voucher_member_name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
