# Generated by Django 3.2.4 on 2021-07-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0003_auto_20210715_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='vouchers',
            name='is_active',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vouchers',
            name='login_user',
            field=models.TextField(default='shsalim'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vouchers',
            name='voucher_display_id',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vouchers',
            name='voucher_date',
            field=models.DateTimeField(),
        ),
    ]
