# Generated by Django 3.2.4 on 2021-07-15 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0005_alter_vouchers_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vouchers',
            name='is_active',
        ),
    ]
