# Generated by Django 3.2.4 on 2021-07-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0006_remove_vouchers_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='vouchers',
            name='is_active',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
