# Generated by Django 3.2.4 on 2021-08-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0007_vouchers_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='vouchers',
            name='voucher_auto_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vouchers',
            name='voucher_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
