# Generated by Django 3.2.4 on 2021-08-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0009_remove_vouchers_voucher_auto_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vouchers',
            name='voucher_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
