# Generated by Django 3.2.4 on 2021-11-11 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0011_vouchers_voucher_auto_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vouchertypes',
            name='voucher_subhead',
        ),
    ]
