# Generated by Django 3.2.4 on 2021-11-11 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0012_remove_vouchertypes_voucher_subhead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vouchertypes',
            name='serial',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
